version: "3.8"
services:
  splat:
    command: /bin/bash
    stdin_open: true
    tty: true
    build: .
    image: xxmatti
    network_mode: host
    environment:
      - DISPLAY
    volumes:
      - type: bind
        source: "${HOME}/.Xauthority"
        target: /root/.Xauthority
      - type: bind
        source: .
        target: /gaussian-splatting
      - type: bind
        source: "${HOME}/Datasets"
        target: /datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              device_ids: ['0']
              capabilities: [gpu]